# Generated by Django 4.2 on 2023-10-09 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tweet", "0004_alter_like_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="./media/uploads", verbose_name="Image"
            ),
        ),
        migrations.AlterField(
            model_name="tweet",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="./media/uploads", verbose_name="Image"
            ),
        ),
        migrations.CreateModel(
            name="CommentLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_likes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_likes",
                        to="tweet.comment",
                        verbose_name="comment",
                    ),
                ),
            ],
            options={
                "unique_together": {("comment", "author")},
            },
        ),
    ]
