# Generated by Django 4.2 on 2023-10-09 13:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tweet", "0006_bookmark"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="bookmark",
            unique_together={("user", "tweet")},
        ),
    ]
