# Generated by Django 4.2 on 2023-10-11 07:00

from django.db import migrations, models
import utils.validators.phone_validation


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_user_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="verified"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                max_length=14,
                unique=True,
                validators=[utils.validators.phone_validation.validate_phone_number],
                verbose_name="Phone number",
            ),
        ),
    ]
